/**
 * generated by Xtext 2.13.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.AbsRuntimeModule;
import org.xtext.AbsStandaloneSetup;
import org.xtext.ide.AbsIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AbsIdeSetup extends AbsStandaloneSetup {
  @Override
  public Injector createInjector() {
    AbsRuntimeModule _absRuntimeModule = new AbsRuntimeModule();
    AbsIdeModule _absIdeModule = new AbsIdeModule();
    return Guice.createInjector(Modules2.mixin(_absRuntimeModule, _absIdeModule));
  }
}
