/**
 * generated by Xtext 2.13.0
 */
package org.xtext.ide;

import org.xtext.ide.AbstractAbsIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AbsIdeModule extends AbstractAbsIdeModule {
}
