/**
 * generated by Xtext 2.13.0
 */
package org.xtext.abs.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.abs.AbsPackage;
import org.xtext.abs.And_expr;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>And expr</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class And_exprImpl extends Pure_expImpl implements And_expr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected And_exprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AbsPackage.Literals.AND_EXPR;
  }

} //And_exprImpl
