/**
 * generated by Xtext 2.13.0
 */
package org.xtext.abs.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.abs.AbsPackage;
import org.xtext.abs.AppOr_exp;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>App Or exp</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class AppOr_expImpl extends Application_conditionImpl implements AppOr_exp
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AppOr_expImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AbsPackage.Literals.APP_OR_EXP;
  }

} //AppOr_expImpl
