/**
 * generated by Xtext 2.13.0
 */
package org.xtext.abs.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.abs.AbsPackage;
import org.xtext.abs.Deltaspec;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Deltaspec</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.abs.impl.DeltaspecImpl#getDeltaspec_param <em>Deltaspec param</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class DeltaspecImpl extends MinimalEObjectImpl.Container implements Deltaspec
{
  /**
   * The cached value of the '{@link #getDeltaspec_param() <em>Deltaspec param</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeltaspec_param()
   * @generated
   * @ordered
   */
  protected EList<String> deltaspec_param;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeltaspecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AbsPackage.Literals.DELTASPEC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getDeltaspec_param()
  {
    if (deltaspec_param == null)
    {
      deltaspec_param = new EDataTypeEList<String>(String.class, this, AbsPackage.DELTASPEC__DELTASPEC_PARAM);
    }
    return deltaspec_param;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AbsPackage.DELTASPEC__DELTASPEC_PARAM:
        return getDeltaspec_param();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AbsPackage.DELTASPEC__DELTASPEC_PARAM:
        getDeltaspec_param().clear();
        getDeltaspec_param().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AbsPackage.DELTASPEC__DELTASPEC_PARAM:
        getDeltaspec_param().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AbsPackage.DELTASPEC__DELTASPEC_PARAM:
        return deltaspec_param != null && !deltaspec_param.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (deltaspec_param: ");
    result.append(deltaspec_param);
    result.append(')');
    return result.toString();
  }

} //DeltaspecImpl
