/**
 * generated by Xtext 2.13.0
 */
package org.xtext.abs.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.abs.AbsPackage;
import org.xtext.abs.Functional_modifier;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Functional modifier</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class Functional_modifierImpl extends Module_modifierImpl implements Functional_modifier
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Functional_modifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AbsPackage.Literals.FUNCTIONAL_MODIFIER;
  }

} //Functional_modifierImpl
