/**
 * generated by Xtext 2.13.0
 */
package org.xtext.abs.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.abs.AbsPackage;
import org.xtext.abs.Guard;
import org.xtext.abs.Object_update_assign_stmt;
import org.xtext.abs.Pure_exp;
import org.xtext.abs.Update_preamble_declaration;
import org.xtext.abs.Var_or_field_ref;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Guard</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.abs.impl.GuardImpl#getVar_or_field_ref <em>Var or field ref</em>}</li>
 *   <li>{@link org.xtext.abs.impl.GuardImpl#getMin <em>Min</em>}</li>
 *   <li>{@link org.xtext.abs.impl.GuardImpl#getMax <em>Max</em>}</li>
 *   <li>{@link org.xtext.abs.impl.GuardImpl#getE <em>E</em>}</li>
 *   <li>{@link org.xtext.abs.impl.GuardImpl#getUpdate_preamble_declaration <em>Update preamble declaration</em>}</li>
 *   <li>{@link org.xtext.abs.impl.GuardImpl#getPre <em>Pre</em>}</li>
 *   <li>{@link org.xtext.abs.impl.GuardImpl#getPost <em>Post</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class GuardImpl extends Object_updateImpl implements Guard
{
  /**
   * The cached value of the '{@link #getVar_or_field_ref() <em>Var or field ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar_or_field_ref()
   * @generated
   * @ordered
   */
  protected Var_or_field_ref var_or_field_ref;

  /**
   * The cached value of the '{@link #getMin() <em>Min</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin()
   * @generated
   * @ordered
   */
  protected Pure_exp min;

  /**
   * The cached value of the '{@link #getMax() <em>Max</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax()
   * @generated
   * @ordered
   */
  protected Pure_exp max;

  /**
   * The cached value of the '{@link #getE() <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getE()
   * @generated
   * @ordered
   */
  protected Pure_exp e;

  /**
   * The cached value of the '{@link #getUpdate_preamble_declaration() <em>Update preamble declaration</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUpdate_preamble_declaration()
   * @generated
   * @ordered
   */
  protected EList<Update_preamble_declaration> update_preamble_declaration;

  /**
   * The cached value of the '{@link #getPre() <em>Pre</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPre()
   * @generated
   * @ordered
   */
  protected EList<Object_update_assign_stmt> pre;

  /**
   * The cached value of the '{@link #getPost() <em>Post</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPost()
   * @generated
   * @ordered
   */
  protected EList<Object_update_assign_stmt> post;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GuardImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AbsPackage.Literals.GUARD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Var_or_field_ref getVar_or_field_ref()
  {
    if (var_or_field_ref != null && var_or_field_ref.eIsProxy())
    {
      InternalEObject oldVar_or_field_ref = (InternalEObject)var_or_field_ref;
      var_or_field_ref = (Var_or_field_ref)eResolveProxy(oldVar_or_field_ref);
      if (var_or_field_ref != oldVar_or_field_ref)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AbsPackage.GUARD__VAR_OR_FIELD_REF, oldVar_or_field_ref, var_or_field_ref));
      }
    }
    return var_or_field_ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Var_or_field_ref basicGetVar_or_field_ref()
  {
    return var_or_field_ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVar_or_field_ref(Var_or_field_ref newVar_or_field_ref)
  {
    Var_or_field_ref oldVar_or_field_ref = var_or_field_ref;
    var_or_field_ref = newVar_or_field_ref;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AbsPackage.GUARD__VAR_OR_FIELD_REF, oldVar_or_field_ref, var_or_field_ref));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Pure_exp getMin()
  {
    return min;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMin(Pure_exp newMin, NotificationChain msgs)
  {
    Pure_exp oldMin = min;
    min = newMin;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AbsPackage.GUARD__MIN, oldMin, newMin);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMin(Pure_exp newMin)
  {
    if (newMin != min)
    {
      NotificationChain msgs = null;
      if (min != null)
        msgs = ((InternalEObject)min).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AbsPackage.GUARD__MIN, null, msgs);
      if (newMin != null)
        msgs = ((InternalEObject)newMin).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AbsPackage.GUARD__MIN, null, msgs);
      msgs = basicSetMin(newMin, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AbsPackage.GUARD__MIN, newMin, newMin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Pure_exp getMax()
  {
    return max;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMax(Pure_exp newMax, NotificationChain msgs)
  {
    Pure_exp oldMax = max;
    max = newMax;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AbsPackage.GUARD__MAX, oldMax, newMax);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMax(Pure_exp newMax)
  {
    if (newMax != max)
    {
      NotificationChain msgs = null;
      if (max != null)
        msgs = ((InternalEObject)max).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AbsPackage.GUARD__MAX, null, msgs);
      if (newMax != null)
        msgs = ((InternalEObject)newMax).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AbsPackage.GUARD__MAX, null, msgs);
      msgs = basicSetMax(newMax, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AbsPackage.GUARD__MAX, newMax, newMax));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Pure_exp getE()
  {
    return e;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetE(Pure_exp newE, NotificationChain msgs)
  {
    Pure_exp oldE = e;
    e = newE;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AbsPackage.GUARD__E, oldE, newE);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setE(Pure_exp newE)
  {
    if (newE != e)
    {
      NotificationChain msgs = null;
      if (e != null)
        msgs = ((InternalEObject)e).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AbsPackage.GUARD__E, null, msgs);
      if (newE != null)
        msgs = ((InternalEObject)newE).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AbsPackage.GUARD__E, null, msgs);
      msgs = basicSetE(newE, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AbsPackage.GUARD__E, newE, newE));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Update_preamble_declaration> getUpdate_preamble_declaration()
  {
    if (update_preamble_declaration == null)
    {
      update_preamble_declaration = new EObjectContainmentEList<Update_preamble_declaration>(Update_preamble_declaration.class, this, AbsPackage.GUARD__UPDATE_PREAMBLE_DECLARATION);
    }
    return update_preamble_declaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Object_update_assign_stmt> getPre()
  {
    if (pre == null)
    {
      pre = new EObjectContainmentEList<Object_update_assign_stmt>(Object_update_assign_stmt.class, this, AbsPackage.GUARD__PRE);
    }
    return pre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Object_update_assign_stmt> getPost()
  {
    if (post == null)
    {
      post = new EObjectContainmentEList<Object_update_assign_stmt>(Object_update_assign_stmt.class, this, AbsPackage.GUARD__POST);
    }
    return post;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AbsPackage.GUARD__MIN:
        return basicSetMin(null, msgs);
      case AbsPackage.GUARD__MAX:
        return basicSetMax(null, msgs);
      case AbsPackage.GUARD__E:
        return basicSetE(null, msgs);
      case AbsPackage.GUARD__UPDATE_PREAMBLE_DECLARATION:
        return ((InternalEList<?>)getUpdate_preamble_declaration()).basicRemove(otherEnd, msgs);
      case AbsPackage.GUARD__PRE:
        return ((InternalEList<?>)getPre()).basicRemove(otherEnd, msgs);
      case AbsPackage.GUARD__POST:
        return ((InternalEList<?>)getPost()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AbsPackage.GUARD__VAR_OR_FIELD_REF:
        if (resolve) return getVar_or_field_ref();
        return basicGetVar_or_field_ref();
      case AbsPackage.GUARD__MIN:
        return getMin();
      case AbsPackage.GUARD__MAX:
        return getMax();
      case AbsPackage.GUARD__E:
        return getE();
      case AbsPackage.GUARD__UPDATE_PREAMBLE_DECLARATION:
        return getUpdate_preamble_declaration();
      case AbsPackage.GUARD__PRE:
        return getPre();
      case AbsPackage.GUARD__POST:
        return getPost();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AbsPackage.GUARD__VAR_OR_FIELD_REF:
        setVar_or_field_ref((Var_or_field_ref)newValue);
        return;
      case AbsPackage.GUARD__MIN:
        setMin((Pure_exp)newValue);
        return;
      case AbsPackage.GUARD__MAX:
        setMax((Pure_exp)newValue);
        return;
      case AbsPackage.GUARD__E:
        setE((Pure_exp)newValue);
        return;
      case AbsPackage.GUARD__UPDATE_PREAMBLE_DECLARATION:
        getUpdate_preamble_declaration().clear();
        getUpdate_preamble_declaration().addAll((Collection<? extends Update_preamble_declaration>)newValue);
        return;
      case AbsPackage.GUARD__PRE:
        getPre().clear();
        getPre().addAll((Collection<? extends Object_update_assign_stmt>)newValue);
        return;
      case AbsPackage.GUARD__POST:
        getPost().clear();
        getPost().addAll((Collection<? extends Object_update_assign_stmt>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AbsPackage.GUARD__VAR_OR_FIELD_REF:
        setVar_or_field_ref((Var_or_field_ref)null);
        return;
      case AbsPackage.GUARD__MIN:
        setMin((Pure_exp)null);
        return;
      case AbsPackage.GUARD__MAX:
        setMax((Pure_exp)null);
        return;
      case AbsPackage.GUARD__E:
        setE((Pure_exp)null);
        return;
      case AbsPackage.GUARD__UPDATE_PREAMBLE_DECLARATION:
        getUpdate_preamble_declaration().clear();
        return;
      case AbsPackage.GUARD__PRE:
        getPre().clear();
        return;
      case AbsPackage.GUARD__POST:
        getPost().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AbsPackage.GUARD__VAR_OR_FIELD_REF:
        return var_or_field_ref != null;
      case AbsPackage.GUARD__MIN:
        return min != null;
      case AbsPackage.GUARD__MAX:
        return max != null;
      case AbsPackage.GUARD__E:
        return e != null;
      case AbsPackage.GUARD__UPDATE_PREAMBLE_DECLARATION:
        return update_preamble_declaration != null && !update_preamble_declaration.isEmpty();
      case AbsPackage.GUARD__PRE:
        return pre != null && !pre.isEmpty();
      case AbsPackage.GUARD__POST:
        return post != null && !post.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //GuardImpl
