/**
 * generated by Xtext 2.13.0
 */
package org.xtext.abs;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Case branch</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.abs.AbsPackage#getCase_branch()
 * @model
 * @generated
 */
public interface Case_branch extends EObject
{
} // Case_branch
