/**
 * generated by Xtext 2.13.0
 */
package org.xtext.abs;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature decl group</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.abs.Feature_decl_group#getO <em>O</em>}</li>
 *   <li>{@link org.xtext.abs.Feature_decl_group#getA <em>A</em>}</li>
 *   <li>{@link org.xtext.abs.Feature_decl_group#getL <em>L</em>}</li>
 *   <li>{@link org.xtext.abs.Feature_decl_group#getU <em>U</em>}</li>
 *   <li>{@link org.xtext.abs.Feature_decl_group#getS <em>S</em>}</li>
 *   <li>{@link org.xtext.abs.Feature_decl_group#getFnode <em>Fnode</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.abs.AbsPackage#getFeature_decl_group()
 * @model
 * @generated
 */
public interface Feature_decl_group extends EObject
{
  /**
   * Returns the value of the '<em><b>O</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>O</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>O</em>' attribute.
   * @see #setO(String)
   * @see org.xtext.abs.AbsPackage#getFeature_decl_group_O()
   * @model
   * @generated
   */
  String getO();

  /**
   * Sets the value of the '{@link org.xtext.abs.Feature_decl_group#getO <em>O</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>O</em>' attribute.
   * @see #getO()
   * @generated
   */
  void setO(String value);

  /**
   * Returns the value of the '<em><b>A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>A</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>A</em>' attribute.
   * @see #setA(String)
   * @see org.xtext.abs.AbsPackage#getFeature_decl_group_A()
   * @model
   * @generated
   */
  String getA();

  /**
   * Sets the value of the '{@link org.xtext.abs.Feature_decl_group#getA <em>A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>A</em>' attribute.
   * @see #getA()
   * @generated
   */
  void setA(String value);

  /**
   * Returns the value of the '<em><b>L</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>L</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>L</em>' attribute.
   * @see #setL(int)
   * @see org.xtext.abs.AbsPackage#getFeature_decl_group_L()
   * @model
   * @generated
   */
  int getL();

  /**
   * Sets the value of the '{@link org.xtext.abs.Feature_decl_group#getL <em>L</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>L</em>' attribute.
   * @see #getL()
   * @generated
   */
  void setL(int value);

  /**
   * Returns the value of the '<em><b>U</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>U</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>U</em>' attribute.
   * @see #setU(int)
   * @see org.xtext.abs.AbsPackage#getFeature_decl_group_U()
   * @model
   * @generated
   */
  int getU();

  /**
   * Sets the value of the '{@link org.xtext.abs.Feature_decl_group#getU <em>U</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>U</em>' attribute.
   * @see #getU()
   * @generated
   */
  void setU(int value);

  /**
   * Returns the value of the '<em><b>S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>S</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' attribute.
   * @see #setS(String)
   * @see org.xtext.abs.AbsPackage#getFeature_decl_group_S()
   * @model
   * @generated
   */
  String getS();

  /**
   * Sets the value of the '{@link org.xtext.abs.Feature_decl_group#getS <em>S</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' attribute.
   * @see #getS()
   * @generated
   */
  void setS(String value);

  /**
   * Returns the value of the '<em><b>Fnode</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.abs.Fnode}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fnode</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fnode</em>' containment reference list.
   * @see org.xtext.abs.AbsPackage#getFeature_decl_group_Fnode()
   * @model containment="true"
   * @generated
   */
  EList<Fnode> getFnode();

} // Feature_decl_group
