/**
 * generated by Xtext 2.13.0
 */
package org.xtext.abs;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Functional modifier</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.abs.AbsPackage#getFunctional_modifier()
 * @model
 * @generated
 */
public interface Functional_modifier extends Module_modifier
{
} // Functional_modifier
