/**
 * generated by Xtext 2.13.0
 */
package org.xtext.abs;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interface decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.abs.Interface_decl#getAnnotations <em>Annotations</em>}</li>
 *   <li>{@link org.xtext.abs.Interface_decl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.abs.Interface_decl#getInterface_name <em>Interface name</em>}</li>
 *   <li>{@link org.xtext.abs.Interface_decl#getMethodsig <em>Methodsig</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.abs.AbsPackage#getInterface_decl()
 * @model
 * @generated
 */
public interface Interface_decl extends EObject
{
  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annotations</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference.
   * @see #setAnnotations(Annotations)
   * @see org.xtext.abs.AbsPackage#getInterface_decl_Annotations()
   * @model containment="true"
   * @generated
   */
  Annotations getAnnotations();

  /**
   * Sets the value of the '{@link org.xtext.abs.Interface_decl#getAnnotations <em>Annotations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Annotations</em>' containment reference.
   * @see #getAnnotations()
   * @generated
   */
  void setAnnotations(Annotations value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.abs.AbsPackage#getInterface_decl_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.abs.Interface_decl#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Interface name</b></em>' reference list.
   * The list contents are of type {@link org.xtext.abs.Interface_decl}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Interface name</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interface name</em>' reference list.
   * @see org.xtext.abs.AbsPackage#getInterface_decl_Interface_name()
   * @model
   * @generated
   */
  EList<Interface_decl> getInterface_name();

  /**
   * Returns the value of the '<em><b>Methodsig</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.abs.Methodsig}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Methodsig</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methodsig</em>' containment reference list.
   * @see org.xtext.abs.AbsPackage#getInterface_decl_Methodsig()
   * @model containment="true"
   * @generated
   */
  EList<Methodsig> getMethodsig();

} // Interface_decl
