/**
 * generated by Xtext 2.13.0
 */
package org.xtext.abs;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trait usage</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.abs.AbsPackage#getTrait_usage()
 * @model
 * @generated
 */
public interface Trait_usage extends EObject
{
} // Trait_usage
