/**
 * generated by Xtext 2.13.0
 */
package org.xtext;

import org.xtext.AbstractAbsRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AbsRuntimeModule extends AbstractAbsRuntimeModule {
}
